# Generated by Django 5.0.7 on 2024-11-04 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0007_profile_delete_relatedmodel"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
