# Generated by Django 5.0.7 on 2024-11-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0011_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="email address"
            ),
        ),
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
