# Generated by Django 5.0.7 on 2024-11-16 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0013_customuser_email_otp_code_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="email_otp_code",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="email_otp_expires",
        ),
    ]
