# Generated by Django 5.0.7 on 2024-11-15 10:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos_app", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="todo",
            old_name="completed",
            new_name="is_special_day",
        ),
        migrations.RemoveField(
            model_name="todo",
            name="description",
        ),
        migrations.AddField(
            model_name="todo",
            name="created_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="todo",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="todo",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("completed", "Completed")],
                default=False,
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="todo",
            name="user",
            field=models.ForeignKey(
                default=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="todos",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="todo",
            name="title",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
