# Generated by Django 5.0.7 on 2024-10-26 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "todos_app",
            "0002_remove_todo_completed_remove_todo_description_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="title",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
