# Generated by Django 5.0.7 on 2024-10-27 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos_app", "0003_alter_todo_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="todo",
            name="priority",
            field=models.CharField(
                choices=[
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                ],
                default="medium",
                max_length=10,
            ),
        ),
    ]
