# Generated by Django 5.0.7 on 2024-10-30 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todos_app", "0004_todo_due_date_todo_priority"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todo",
            name="priority",
        ),
    ]
