# Generated by Django 5.0.7 on 2024-10-30 05:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos_app", "0005_remove_todo_priority"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="created_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="todo",
            name="is_special_day",
            field=models.BooleanField(default=False),
        ),
    ]
